name: interface_carte_grise
description: Interface pour la gestion de carte grise.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI et Responsive
  flutter_screenutil: ^5.7.0
  http: ^1.1.0

  # Internationalisation
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700