# Generated by Django 5.1.4 on 2024-12-13 20:22

import api_carte_grise.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('photo', models.CharField(choices=api_carte_grise.models.get_proprietaire_image_choices, help_text='Sélectionnez une image du dossier static/img/proprietaires', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('photo', models.CharField(choices=api_carte_grise.models.get_vehicule_image_choices, help_text='Sélectionnez une image du dossier static/img/vehicules', max_length=255)),
                ('date_fin_assurance', models.DateField()),
                ('date_controle_technique', models.DateField()),
                ('poids', models.IntegerField()),
                ('date_mise_circulation', models.DateField()),
                ('type_moteur', models.CharField(max_length=50)),
                ('puissance', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('consommation', models.CharField(max_length=50)),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_carte_grise.proprietaire')),
            ],
        ),
    ]
